# Automatically generated by make.py from ['rules.py']

_out/j/j_dumper.o: j/j_dumper.cpp
	mkdir -p _out/j
	g++ -Wall -Wextra -g -fdiagnostics-color=always -Og --coverage -o _out/j/j_dumper.o -c j/j_dumper.cpp -MD -MP

-include _out/j/j_dumper.d

_out/j/j_parser.o: j/j_parser.cpp
	mkdir -p _out/j
	g++ -Wall -Wextra -g -fdiagnostics-color=always -Og --coverage -o _out/j/j_parser.o -c j/j_parser.cpp -MD -MP

-include _out/j/j_parser.d

_out/j/j_reader.o: j/j_reader.cpp
	mkdir -p _out/j
	g++ -Wall -Wextra -g -fdiagnostics-color=always -Og --coverage -o _out/j/j_reader.o -c j/j_reader.cpp -MD -MP

-include _out/j/j_reader.d

_out/j/j_writer.o: j/j_writer.cpp
	mkdir -p _out/j
	g++ -Wall -Wextra -g -fdiagnostics-color=always -Og --coverage -o _out/j/j_writer.o -c j/j_writer.cpp -MD -MP

-include _out/j/j_writer.d

_out/tests/test_parser.o: tests/test_parser.cpp
	mkdir -p _out/tests
	g++ -Wall -Wextra -g -fdiagnostics-color=always -Og --coverage -o _out/tests/test_parser.o -c tests/test_parser.cpp -MD -MP

-include _out/tests/test_parser.d

_out/tests/test_dumper.o: tests/test_dumper.cpp
	mkdir -p _out/tests
	g++ -Wall -Wextra -g -fdiagnostics-color=always -Og --coverage -o _out/tests/test_dumper.o -c tests/test_dumper.cpp -MD -MP

-include _out/tests/test_dumper.d

_out/tests/test_run_json_test_suite.o: tests/test_run_json_test_suite.cpp
	mkdir -p _out/tests
	g++ -Wall -Wextra -g -fdiagnostics-color=always -Og --coverage -o _out/tests/test_run_json_test_suite.o -c tests/test_run_json_test_suite.cpp -MD -MP

-include _out/tests/test_run_json_test_suite.d

test_parser: _out/j/j_dumper.o _out/j/j_parser.o _out/j/j_reader.o _out/j/j_writer.o _out/tests/test_parser.o
	g++ -coverage -o test_parser _out/j/j_dumper.o _out/j/j_parser.o _out/j/j_reader.o _out/j/j_writer.o _out/tests/test_parser.o

test_dumper: _out/j/j_dumper.o _out/j/j_parser.o _out/j/j_reader.o _out/j/j_writer.o _out/tests/test_dumper.o
	g++ -coverage -o test_dumper _out/j/j_dumper.o _out/j/j_parser.o _out/j/j_reader.o _out/j/j_writer.o _out/tests/test_dumper.o

test_run_json_test_suite: _out/j/j_dumper.o _out/j/j_parser.o _out/j/j_reader.o _out/j/j_writer.o _out/tests/test_run_json_test_suite.o
	g++ -coverage -o test_run_json_test_suite _out/j/j_dumper.o _out/j/j_parser.o _out/j/j_reader.o _out/j/j_writer.o _out/tests/test_run_json_test_suite.o

test: test_parser test_dumper test_run_json_test_suite
	true

lcov-zero: 
	lcov --directory . --zerocounters

lcov-html: 
	lcov --directory . --capture --include '/cygdrive/c/tanzhuo/nosj/*' --rc lcov_branch_coverage=1 --output-file _out/cov.info
	genhtml --prefix /cygdrive/c/tanzhuo/nosj --rc lcov_branch_coverage=1 _out/cov.info --output-directory=lcov-html

